package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Articlecomment generated by hbm2java
 */
public class Articlecomment implements java.io.Serializable {

	private Long acId;
	private Long acArticleId;
	private Long acAuthorId;
	private String acContent;
	private Date acIndate;

	public Articlecomment() {
	}

	public Articlecomment(Long acArticleId, Long acAuthorId, String acContent,
			Date acIndate) {
		this.acArticleId = acArticleId;
		this.acAuthorId = acAuthorId;
		this.acContent = acContent;
		this.acIndate = acIndate;
	}

	public Long getAcId() {
		return this.acId;
	}

	public void setAcId(Long acId) {
		this.acId = acId;
	}

	public Long getAcArticleId() {
		return this.acArticleId;
	}

	public void setAcArticleId(Long acArticleId) {
		this.acArticleId = acArticleId;
	}

	public Long getAcAuthorId() {
		return this.acAuthorId;
	}

	public void setAcAuthorId(Long acAuthorId) {
		this.acAuthorId = acAuthorId;
	}

	public String getAcContent() {
		return this.acContent;
	}

	public void setAcContent(String acContent) {
		this.acContent = acContent;
	}

	public Date getAcIndate() {
		return this.acIndate;
	}

	public void setAcIndate(Date acIndate) {
		this.acIndate = acIndate;
	}

}
