package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Long AId;
	private Long AAuthorId;
	private String ATitle;
	private String AContent;
	private Date AIndate;
	private Integer ARead;

	public Article() {
	}

	public Article(Long AAuthorId, String ATitle, String AContent,
			Date AIndate, Integer ARead) {
		this.AAuthorId = AAuthorId;
		this.ATitle = ATitle;
		this.AContent = AContent;
		this.AIndate = AIndate;
		this.ARead = ARead;
	}

	public Long getAId() {
		return this.AId;
	}

	public void setAId(Long AId) {
		this.AId = AId;
	}

	public Long getAAuthorId() {
		return this.AAuthorId;
	}

	public void setAAuthorId(Long AAuthorId) {
		this.AAuthorId = AAuthorId;
	}

	public String getATitle() {
		return this.ATitle;
	}

	public void setATitle(String ATitle) {
		this.ATitle = ATitle;
	}

	public String getAContent() {
		return this.AContent;
	}

	public void setAContent(String AContent) {
		this.AContent = AContent;
	}

	public Date getAIndate() {
		return this.AIndate;
	}

	public void setAIndate(Date AIndate) {
		this.AIndate = AIndate;
	}

	public Integer getARead() {
		return this.ARead;
	}

	public void setARead(Integer ARead) {
		this.ARead = ARead;
	}

}
