package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private Integer EId;
	private String EName;

	public Email() {
	}

	public Email(String EName) {
		this.EName = EName;
	}

	public Integer getEId() {
		return this.EId;
	}

	public void setEId(Integer EId) {
		this.EId = EId;
	}

	public String getEName() {
		return this.EName;
	}

	public void setEName(String EName) {
		this.EName = EName;
	}

}
