package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Friendapply generated by hbm2java
 */
public class Friendapply implements java.io.Serializable {

	private Long faId;
	private Long faSendId;
	private Long faGetId;
	private String faInfo;

	public Friendapply() {
	}

	public Friendapply(Long faSendId, Long faGetId, String faInfo) {
		this.faSendId = faSendId;
		this.faGetId = faGetId;
		this.faInfo = faInfo;
	}

	public Long getFaId() {
		return this.faId;
	}

	public void setFaId(Long faId) {
		this.faId = faId;
	}

	public Long getFaSendId() {
		return this.faSendId;
	}

	public void setFaSendId(Long faSendId) {
		this.faSendId = faSendId;
	}

	public Long getFaGetId() {
		return this.faGetId;
	}

	public void setFaGetId(Long faGetId) {
		this.faGetId = faGetId;
	}

	public String getFaInfo() {
		return this.faInfo;
	}

	public void setFaInfo(String faInfo) {
		this.faInfo = faInfo;
	}

}
