package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private Long FId;
	private Long FHostId;
	private Long FFriendId;
	private Integer FType;
	private String FDesc;

	public Friend() {
	}

	public Friend(Long FHostId, Long FFriendId, Integer FType, String FDesc) {
		this.FHostId = FHostId;
		this.FFriendId = FFriendId;
		this.FType = FType;
		this.FDesc = FDesc;
	}

	public Long getFId() {
		return this.FId;
	}

	public void setFId(Long FId) {
		this.FId = FId;
	}

	public Long getFHostId() {
		return this.FHostId;
	}

	public void setFHostId(Long FHostId) {
		this.FHostId = FHostId;
	}

	public Long getFFriendId() {
		return this.FFriendId;
	}

	public void setFFriendId(Long FFriendId) {
		this.FFriendId = FFriendId;
	}

	public Integer getFType() {
		return this.FType;
	}

	public void setFType(Integer FType) {
		this.FType = FType;
	}

	public String getFDesc() {
		return this.FDesc;
	}

	public void setFDesc(String FDesc) {
		this.FDesc = FDesc;
	}

}
