package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Gossiptip generated by hbm2java
 */
public class Gossiptip implements java.io.Serializable {

	private Long gtId;
	private Long gtSendId;
	private Long gtGetId;
	private String gtUrl;
	private Date gtDate;
	private Integer gtStatus;

	public Gossiptip() {
	}

	public Gossiptip(Long gtSendId, Long gtGetId, String gtUrl, Date gtDate,
			Integer gtStatus) {
		this.gtSendId = gtSendId;
		this.gtGetId = gtGetId;
		this.gtUrl = gtUrl;
		this.gtDate = gtDate;
		this.gtStatus = gtStatus;
	}

	public Long getGtId() {
		return this.gtId;
	}

	public void setGtId(Long gtId) {
		this.gtId = gtId;
	}

	public Long getGtSendId() {
		return this.gtSendId;
	}

	public void setGtSendId(Long gtSendId) {
		this.gtSendId = gtSendId;
	}

	public Long getGtGetId() {
		return this.gtGetId;
	}

	public void setGtGetId(Long gtGetId) {
		this.gtGetId = gtGetId;
	}

	public String getGtUrl() {
		return this.gtUrl;
	}

	public void setGtUrl(String gtUrl) {
		this.gtUrl = gtUrl;
	}

	public Date getGtDate() {
		return this.gtDate;
	}

	public void setGtDate(Date gtDate) {
		this.gtDate = gtDate;
	}

	public Integer getGtStatus() {
		return this.gtStatus;
	}

	public void setGtStatus(Integer gtStatus) {
		this.gtStatus = gtStatus;
	}

}
