package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Gossip generated by hbm2java
 */
public class Gossip implements java.io.Serializable {

	private Long GId;
	private Long GSendId;
	private Long GGetId;
	private String GContent;
	private Date GIndate;

	public Gossip() {
	}

	public Gossip(Long GSendId, Long GGetId, String GContent, Date GIndate) {
		this.GSendId = GSendId;
		this.GGetId = GGetId;
		this.GContent = GContent;
		this.GIndate = GIndate;
	}

	public Long getGId() {
		return this.GId;
	}

	public void setGId(Long GId) {
		this.GId = GId;
	}

	public Long getGSendId() {
		return this.GSendId;
	}

	public void setGSendId(Long GSendId) {
		this.GSendId = GSendId;
	}

	public Long getGGetId() {
		return this.GGetId;
	}

	public void setGGetId(Long GGetId) {
		this.GGetId = GGetId;
	}

	public String getGContent() {
		return this.GContent;
	}

	public void setGContent(String GContent) {
		this.GContent = GContent;
	}

	public Date getGIndate() {
		return this.GIndate;
	}

	public void setGIndate(Date GIndate) {
		this.GIndate = GIndate;
	}

}
