package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Jobinfo generated by hbm2java
 */
public class Jobinfo implements java.io.Serializable {

	private Integer jiId;
	private String jiName;
	private Integer jiJobId;

	public Jobinfo() {
	}

	public Jobinfo(String jiName, Integer jiJobId) {
		this.jiName = jiName;
		this.jiJobId = jiJobId;
	}

	public Integer getJiId() {
		return this.jiId;
	}

	public void setJiId(Integer jiId) {
		this.jiId = jiId;
	}

	public String getJiName() {
		return this.jiName;
	}

	public void setJiName(String jiName) {
		this.jiName = jiName;
	}

	public Integer getJiJobId() {
		return this.jiJobId;
	}

	public void setJiJobId(Integer jiJobId) {
		this.jiJobId = jiJobId;
	}

}
