package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Localprovince generated by hbm2java
 */
public class Localprovince implements java.io.Serializable {

	private int lpId;
	private String lpName;

	public Localprovince() {
	}

	public Localprovince(int lpId, String lpName) {
		this.lpId = lpId;
		this.lpName = lpName;
	}

	public int getLpId() {
		return this.lpId;
	}

	public void setLpId(int lpId) {
		this.lpId = lpId;
	}

	public String getLpName() {
		return this.lpName;
	}

	public void setLpName(String lpName) {
		this.lpName = lpName;
	}

}
