package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * Newsrelation generated by hbm2java
 */
public class Newsrelation implements java.io.Serializable {

	private Long nrId;
	private Long nrNewsId;
	private Long nrFriendId;
	private Integer nrStatus;

	public Newsrelation() {
	}

	public Newsrelation(Long nrNewsId, Long nrFriendId, Integer nrStatus) {
		this.nrNewsId = nrNewsId;
		this.nrFriendId = nrFriendId;
		this.nrStatus = nrStatus;
	}

	public Long getNrId() {
		return this.nrId;
	}

	public void setNrId(Long nrId) {
		this.nrId = nrId;
	}

	public Long getNrNewsId() {
		return this.nrNewsId;
	}

	public void setNrNewsId(Long nrNewsId) {
		this.nrNewsId = nrNewsId;
	}

	public Long getNrFriendId() {
		return this.nrFriendId;
	}

	public void setNrFriendId(Long nrFriendId) {
		this.nrFriendId = nrFriendId;
	}

	public Integer getNrStatus() {
		return this.nrStatus;
	}

	public void setNrStatus(Integer nrStatus) {
		this.nrStatus = nrStatus;
	}

}
