package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Long NId;
	private String NTitle;
	private Long NHostId;
	private String NContent;
	private Integer NType;
	private Date NDate;

	public News() {
	}

	public News(String NTitle, Long NHostId, String NContent, Integer NType,
			Date NDate) {
		this.NTitle = NTitle;
		this.NHostId = NHostId;
		this.NContent = NContent;
		this.NType = NType;
		this.NDate = NDate;
	}

	public Long getNId() {
		return this.NId;
	}

	public void setNId(Long NId) {
		this.NId = NId;
	}

	public String getNTitle() {
		return this.NTitle;
	}

	public void setNTitle(String NTitle) {
		this.NTitle = NTitle;
	}

	public Long getNHostId() {
		return this.NHostId;
	}

	public void setNHostId(Long NHostId) {
		this.NHostId = NHostId;
	}

	public String getNContent() {
		return this.NContent;
	}

	public void setNContent(String NContent) {
		this.NContent = NContent;
	}

	public Integer getNType() {
		return this.NType;
	}

	public void setNType(Integer NType) {
		this.NType = NType;
	}

	public Date getNDate() {
		return this.NDate;
	}

	public void setNDate(Date NDate) {
		this.NDate = NDate;
	}

}
