package com.myxiaonei.domain;

// Generated 2018-2-28 14:05:53 by Hibernate Tools 3.4.0.CR1

/**
 * University generated by hbm2java
 */
public class University implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer countryId;
	private Integer proId;

	public University() {
	}

	public University(String name) {
		this.name = name;
	}

	public University(String name, Integer countryId, Integer proId) {
		this.name = name;
		this.countryId = countryId;
		this.proId = proId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public Integer getProId() {
		return this.proId;
	}

	public void setProId(Integer proId) {
		this.proId = proId;
	}

}
