package com.myxiaonei.domain;

// Generated 2018-2-28 15:04:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitor generated by hbm2java
 */
@Entity
@Table(name = "visitor")
public class Visitor implements java.io.Serializable {

	private Long VId;
	private Long VHostId;
	private Long VVisitorId;
	private Date VDate;

	public Visitor() {
	}

	public Visitor(Long VHostId, Long VVisitorId, Date VDate) {
		this.VHostId = VHostId;
		this.VVisitorId = VVisitorId;
		this.VDate = VDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "v_id", unique = true, nullable = false)
	public Long getVId() {
		return this.VId;
	}

	public void setVId(Long VId) {
		this.VId = VId;
	}

	@Column(name = "v_hostId")
	public Long getVHostId() {
		return this.VHostId;
	}

	public void setVHostId(Long VHostId) {
		this.VHostId = VHostId;
	}

	@Column(name = "v_visitorId")
	public Long getVVisitorId() {
		return this.VVisitorId;
	}

	public void setVVisitorId(Long VVisitorId) {
		this.VVisitorId = VVisitorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "v_date", length = 19)
	public Date getVDate() {
		return this.VDate;
	}

	public void setVDate(Date VDate) {
		this.VDate = VDate;
	}

}
